version: "3.3"

services:
#  postgresql:
#    build:
#      context: postgresql
#    environment:
#      POSTGRES_PASSWORD: root
#      POSTGRES_USER: root
#    ports:
#      - "5432:5432"

  mysql:
    build:
      context: mysql
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=default
      - MYSQL_PASSWORD=default
    ports:
      - "3306:3306"

  phpadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    environment:
      - PMA_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - PMA_HOST=mysql
      - PMA_PORT=3306
    ports:
      - "8081:80"

